#!/bin/bash

cp node_modules/angular/angular.min.js js/angular.js
#cp node_modules/angular-animate/angular-animate.min.js js/angular-animate.js
#cp node_modules/jquery/dist/jquery.min.js js/jquery.js
